# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'InClass07' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for InClass07
    pod 'Alamofire', '~> 5.0.0-beta.3'
    pod 'SwiftyJSON', '~> 4.0'

  target 'InClass07Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'InClass07UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
